variable "name" {}
variable "region" {}
variable "aws_instance_ami" {}
variable "aws_instance_type" {}
variable "ssh_key_name" {}
variable "redash_ami" {}
variable "redash_instance_type" {}
variable "elasticache_node_type" {}
variable "aws_db_instance_class" {}
variable "aws_db_username" {}
variable "aws_db_password" {}
variable "aws_web_domain" {}
variable "aws_web_subdomain" {}
variable "ssh_public_key_path" {}
variable "ssh_private_key_path" {}
variable "aws_credentials_path" {}
variable "aws_credentials_profile_name" {}
variable "s3_remote_state_bucket" {}
variable "s3_remote_state_network_common_key" {}
variable "s3_remote_state_network_env_key" {}